AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  strecho - lambda function to support the strech alexa skill 
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  StrechoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../../dist/
      Handler: strecho.out 
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html

Outputs:
  StrechoFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt StrechoFunction.Arn
  StrechoFunctionIamRole:
    Description: "Implicit IAM Role created for strecho function"
    Value: !GetAtt StrechoFunction.Arn
