// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/strava_client.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	gomock "github.com/golang/mock/gomock"
	go_strava "github.com/strava/go.strava"
	reflect "reflect"
)

// MockStravaClient is a mock of StravaClient interface
type MockStravaClient struct {
	ctrl     *gomock.Controller
	recorder *MockStravaClientMockRecorder
}

// MockStravaClientMockRecorder is the mock recorder for MockStravaClient
type MockStravaClientMockRecorder struct {
	mock *MockStravaClient
}

// NewMockStravaClient creates a new mock instance
func NewMockStravaClient(ctrl *gomock.Controller) *MockStravaClient {
	mock := &MockStravaClient{ctrl: ctrl}
	mock.recorder = &MockStravaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStravaClient) EXPECT() *MockStravaClientMockRecorder {
	return m.recorder
}

// GetAthlete mocks base method
func (m *MockStravaClient) GetAthlete() (*go_strava.AthleteDetailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAthlete")
	ret0, _ := ret[0].(*go_strava.AthleteDetailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAthlete indicates an expected call of GetAthlete
func (mr *MockStravaClientMockRecorder) GetAthlete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAthlete", reflect.TypeOf((*MockStravaClient)(nil).GetAthlete))
}

// GetLast24HoursOfActivity mocks base method
func (m *MockStravaClient) GetLast24HoursOfActivity() ([]*go_strava.ActivitySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast24HoursOfActivity")
	ret0, _ := ret[0].([]*go_strava.ActivitySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLast24HoursOfActivity indicates an expected call of GetLast24HoursOfActivity
func (mr *MockStravaClientMockRecorder) GetLast24HoursOfActivity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast24HoursOfActivity", reflect.TypeOf((*MockStravaClient)(nil).GetLast24HoursOfActivity))
}
